# Generated by Django 5.0.4 on 2024-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('fuentes', models.URLField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='alma1',
        ),
    ]
